# Generated by Django 2.2.13 on 2020-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200614_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='project',
        ),
        migrations.AddField(
            model_name='pad',
            name='project',
            field=models.ManyToManyField(null=True, to='project.Project'),
        ),
    ]
